"""Add recipe_type column

Revision ID: 3db737c961e3
Revises: 
Create Date: 2024-05-14 22:59:43.693699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db737c961e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_type', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('is_recipe', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('ingredients', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('recipe_instructions', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('cuisine_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cuisine_style', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('difficulty_level', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.drop_column('image_filename')
        batch_op.drop_column('difficulty_level')
        batch_op.drop_column('cuisine_style')
        batch_op.drop_column('cuisine_type')
        batch_op.drop_column('recipe_instructions')
        batch_op.drop_column('ingredients')
        batch_op.drop_column('is_recipe')
        batch_op.drop_column('recipe_type')

    # ### end Alembic commands ###
